name    'ehazlett-memcached'
version '0.0.1'
source ''
author 'ehazlett'
license 'Apache License, Version 2.0'
summary 'Installs and configures memcached'
description ''
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
