name    'ehazlett-mongodb'
version '0.0.1'
source 'https://github.com/ehazlett/opencloud.core/'
author 'ehazlett'
license 'Apache License Version 2.0'
summary 'Installs and configures MongoDB'
description 'Installs and configures MongoDB'
project_page 'https://github.com/ehazlett/opencloud.core/'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
